version: '3'
services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "4002:27017"
    restart: always

  video-storage:
    image: video-storage
    build: 
      context: ./video-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4000:80"
    environment:
      - PORT=80
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-with-history
    container_name: video-streaming
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
    restart: "no"
    depends_on:
      - db
  history:
    image: history
    build: 
      context: ./history
      dockerfile: Dockerfile
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=history 
    restart: "no"
    depends_on:
      - db