version: '3'
services:
  video-storage:
    image: video-storage
    init: true
    ports:
      - "4000:4000"
    networks:
      - internal_video_storage
      - traefik_public
    labels:
      # traefik
      - traefik.enable=true
      - traefik.docker.network=traefik_public
      # traefikv2
      - "traefik.http.routers.video_storage_1.rule==Host(`${SELF_PATH_1}`)"
      - "traefik.http.routers.video_storage_1.entrypoints=http"
      - "traefik.http.services.eq2_gmaps_1.loadbalancer.server.port=4000"

    build: 
      context: .
      dockerfile: Dockerfile
    container_name: video-storage
    environment:
      - SELF_URL=http://${SELF_PATH_1:-127.0.0.1}
      - PORT=4000
    restart: "no"

networks:
  traefik_public:
    external: true
  internal_video_storage: